name: build angular

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: w
      run: ls
    - name: Install dependencies
      run: npm run install --prefix src/webapp/TourneyRent

    - name: Build
      run: npm run build --prefix src/webapp/TourneyRent